[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
failure = "0.1.8"
log = "0.4.21"
rust-crypto = "0.2.36"
serde = {version = "1.0.202", features = ["derive"]}
sled = "0.34.7"


[lib]
path = "src/block.rs"

